name: Pipeline-to AWS-Elastic-Beanstalk
env:
  EB_APPLICATION_NAME    : "lavagna"
  EB_ENVIRONMENT_NAME    : "Lavagna-loadbalancer-github-actions-env"

  AWS_REGION_NAME        : "us-east-1"

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    
     - name: Check out the code
       uses: actions/checkout@v2
 
     - name: Create ZIP for EB
       run: zip -r dockerfiles.zip . -x '*.git*'
       
     - name: Check archive
       run: pwd

  
